Repository micronaut-projects/micronaut-build, pull requests merged in 2020-08, with the labels that each got.

#33 fix: delete individual pages
  src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy
Labels: type: docs

#35 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#40 Try to fix release process
  .github/workflows/release.yml
Labels: relates-to: build

#41 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#44 bump up micronaut docs to 1.0.24
  gradle.properties
Labels: relates-to: build
