Repository micronaut-projects/micronaut-build, pull requests merged in 2022-07, with the labels that each got.

#361 Fix binary compatibility checks
  build.gradle
  src/main/groovy/io/micronaut/build/compat/JavaBridgeAndSyntheticRule.java
  src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
  src/main/java/io/micronaut/build/compat/FindBaselineTask.java
Labels: bug

#370 Check version catalog compatibility
  src/main/groovy/io/micronaut/build/MicronautBomPlugin.java
  src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
  src/main/groovy/io/micronaut/build/compat/VersionCatalogCompatibilityCheck.java
  src/main/groovy/io/micronaut/build/pom/BomSuppressions.java
  src/test/groovy/io/micronaut/build/compat/VersionCatalogCompatibilityCheckTest.groovy
  src/test/resources/baseline.toml
  src/test/resources/current.toml
Labels: type: improvement

#372 Fix dependency on baseline task
  src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
Labels: type: bug

#373 Properly fix dependency
  src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
Labels: type: bug

#376 bug: disabled binarycompat should skip checkVersionCatalogCompatibility
  src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
Labels: bug
