Repository micronaut-projects/micronaut-build, pull requests merged in 2022-03, with the labels that each got.

#281 Allow version catalogs to include aliases from nested catalogs
  src/functionalTest/gradle-projects/test-bom-module/build.gradle
  src/functionalTest/gradle-projects/test-bom-module/gradle.properties
  src/functionalTest/gradle-projects/test-bom-module/gradle/libs.versions.toml
  src/functionalTest/gradle-projects/test-bom-module/settings.gradle
  src/functionalTest/groovy/io/micronaut/build/catalogs/BomGenerationFunctionalTest.groovy
  src/functionalTest/groovy/io/micronaut/build/quality/QualityReportingPluginFunctionalTest.groovy
  src/main/groovy/io/micronaut/build/MicronautBomPlugin.java
  src/main/groovy/io/micronaut/build/pom/MicronautBomExtension.java
  src/main/groovy/io/micronaut/build/pom/VersionCatalogConverter.groovy
Labels: type: improvement

#282 Add binary compatibility checks
  build.gradle
  gradle.properties
  src/main/groovy/io/micronaut/build/MicronautBaseModulePlugin.groovy
  src/main/groovy/io/micronaut/build/compat/AcceptanceHelper.groovy
  src/main/groovy/io/micronaut/build/compat/AcceptedApiChange.java
  src/main/groovy/io/micronaut/build/compat/AcceptedApiChangesParser.groovy
  src/main/groovy/io/micronaut/build/compat/AcceptedApiChangesRule.java
  src/main/groovy/io/micronaut/build/compat/BinaryCompatibibilityExtension.java
  src/main/groovy/io/micronaut/build/compat/InternalAnnotationCollectorRule.java
  src/main/groovy/io/micronaut/build/compat/InternalAnnotationPostProcessRule.java
  src/main/groovy/io/micronaut/build/compat/InternalMicronautTypeRule.java
  src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
  src/main/java/io/micronaut/build/compat/FindBaselineTask.java
  src/main/java/io/micronaut/build/compat/VersionModel.java
  src/test/groovy/io/micronaut/build/compat/VersionModelTest.groovy
Labels: type: improvement

#285 Use a single version for all project properties in BOM/catalog
  src/functionalTest/gradle-projects/multi-project-bom/build.gradle
  src/functionalTest/gradle-projects/multi-project-bom/freedom-bar/build.gradle
  src/functionalTest/gradle-projects/multi-project-bom/freedom-bom/build.gradle
  src/functionalTest/gradle-projects/multi-project-bom/freedom-foo/build.gradle
  src/functionalTest/gradle-projects/multi-project-bom/gradle.properties
  src/functionalTest/gradle-projects/multi-project-bom/settings.gradle
  src/functionalTest/groovy/io/micronaut/build/AbstractFunctionalTest.groovy
  src/functionalTest/groovy/io/micronaut/build/catalogs/BomGenerationFunctionalTest.groovy
  src/main/groovy/io/micronaut/build/MicronautBomPlugin.java
  src/main/groovy/io/micronaut/build/pom/MicronautBomExtension.java
Labels: bug

#291 Extract Gradle Enterprise configuration
  build.gradle
  src/main/java/io/micronaut/build/MicronautBuildSettingsPlugin.java
  src/main/java/io/micronaut/build/MicronautGradleEnterprisePlugin.java
  src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
  src/main/java/io/micronaut/build/ProviderUtils.java
Labels: type: improvement

#298 Map the runtime scope to runtimeOnly for doc snippets
  src/main/groovy/io/micronaut/docs/BuildDependencyMacro.groovy
  src/test/groovy/io/micronaut/docs/BuildDependencyMacroSpec.groovy
Labels: documentation

#305 Fix how catalogs are updated on CI
  src/main/java/io/micronaut/build/catalogs/MicronautVersionCatalogUpdatePlugin.java
  src/main/java/io/micronaut/build/catalogs/tasks/VersionCatalogUpdate.java
Labels: bug

#307 Fix POM parser not substituting properties in properties
  src/main/groovy/io/micronaut/build/pom/PomFile.java
  src/main/groovy/io/micronaut/build/pom/PomParser.groovy
  src/test/groovy/io/micronaut/build/pom/PomParserTest.groovy
Labels: bug
