Repository micronaut-projects/micronaut-build, pull requests merged in 2023-02, with the labels that each got.

#481 Populate user agent header for Github Requests
  src/main/java/io/micronaut/build/utils/GithubApiUtils.java
Labels: bug

#484 Introduce GitHub API as a build service
  src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy
  src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
  src/main/groovy/io/micronaut/docs/dropdown/CreateReleaseDropDownTask.groovy
  src/main/java/io/micronaut/build/compat/FindBaselineTask.java
  src/main/java/io/micronaut/build/utils/GitHubApiService.java
  src/main/java/io/micronaut/build/utils/GithubApiUtils.java
Labels: type: bug

#486 Fix race condition when verifying BOM
  src/main/groovy/io/micronaut/build/pom/PomDownloader.java
Labels: bug

#518 Disable Jacoco on local builds
  src/main/java/io/micronaut/build/MicronautQualityChecksParticipantPlugin.java
Labels: type: improvement

#519 Make it possible to run tests on specific JDK
  src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
Labels: type: improvement
