Repository micronaut-projects/micronaut-build, pull requests merged in 2023-03, with the labels that each got.

#521 Fix binary compatibility checks
  src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
Labels: bug

#523 Fix build settings extension method visibility
  src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java
Labels: type: bug

#526 Add java details as tags to the build scan
  src/main/java/io/micronaut/build/MicronautGradleEnterprisePlugin.java
Labels: enhancement

#532 Add more options to configure standard project names
  src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java
  src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
Labels: type: improvement

#533 Fix Maven repository URL
  src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
Labels: type: bug

#534 Introduce pre-release check task
  src/functionalTest/groovy/io/micronaut/build/AbstractFunctionalTest.groovy
  src/functionalTest/groovy/io/micronaut/build/quality/PreReleaseFunctionalTest.groovy
  src/main/groovy/io/micronaut/build/MicronautBaseModulePlugin.groovy
  src/main/groovy/io/micronaut/build/MicronautBomPlugin.java
  src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy
  src/main/groovy/io/micronaut/build/pom/PomChecker.groovy
  src/main/groovy/io/micronaut/build/pom/PomCheckerUtils.java
  src/main/java/io/micronaut/build/MicronautBuildExtension.java
  src/main/java/io/micronaut/build/MicronautPlugin.java
  src/main/java/io/micronaut/build/pom/BomSuppressions.java
Labels: type: improvement

#540 Fix AOT test fixtures coordinates
  src/main/groovy/io/micronaut/build/aot/MicronautAotModulePlugin.java
Labels: type: bug
